package com.example.securityapi.controller;
import java.time.*; import java.util.*; import jakarta.validation.constraints.*; import org.springframework.http.*; import org.springframework.security.authentication.*; import org.springframework.security.core.*; import org.springframework.web.bind.annotation.*; import org.springframework.security.access.prepost.PreAuthorize; import com.example.securityapi.security.JwtService; import com.example.securityapi.model.Entities.*; import com.example.securityapi.repository.Repositories.*;
@RestController public class AuthController { private final AuthenticationManager auth; private final JwtService jwt; private final UserRepository users; private final CredentialRepository credentials; public AuthController(AuthenticationManager a,JwtService j,UserRepository u,CredentialRepository c){auth=a;jwt=j;users=u;credentials=c;} public record Login(@NotBlank String username,@NotBlank String password){} public record Refresh(@NotBlank String refreshToken){} public record Tokens(String accessToken,String refreshToken){} public record Credential(@NotBlank String provider,@NotBlank String accessToken,@NotBlank String refreshToken){}
 @PostMapping("/api/auth/login") public Tokens login(@RequestBody Login r){Authentication a=auth.authenticate(new UsernamePasswordAuthenticationToken(r.username(),r.password()));return tokens(users.findByUsername(a.getName()).orElseThrow());}
 @PostMapping("/api/auth/refresh") public Tokens refresh(@RequestBody Refresh r){var c=jwt.claims(r.refreshToken());if(!"refresh".equals(c.get("type")))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED);return tokens(users.findByUsername(c.getSubject()).orElseThrow());}
 @GetMapping("/api/user/profile") @PreAuthorize("hasAnyRole('USER','ADMIN')") public Map<String,String> profile(Authentication a){return Map.of("username",a.getName(),"message","Authenticated user access granted");}
 @GetMapping("/api/admin/audit") @PreAuthorize("hasRole('ADMIN')") public Map<String,String> audit(){return Map.of("message","Admin-only audit access granted");}
 @PostMapping("/api/user/credentials") @PreAuthorize("hasAnyRole('USER','ADMIN')") public ResponseEntity<Map<String,String>> store(Authentication a,@RequestBody Credential r){var u=users.findByUsername(a.getName()).orElseThrow();credentials.save(new OAuthCredential(r.provider(),jwt.encrypt(r.accessToken()),jwt.encrypt(r.refreshToken()),u));return ResponseEntity.status(HttpStatus.CREATED).body(Map.of("message","Credentials encrypted and stored"));}
 private Tokens tokens(AppUser u){return new Tokens(jwt.token(u.getUsername(),u.getRole(),"access",Duration.ofMinutes(15)),jwt.token(u.getUsername(),u.getRole(),"refresh",Duration.ofDays(7)));} }
